# Generated by Django 5.1.6 on 2025-03-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_index', models.FloatField()),
                ('discharge_time', models.FloatField()),
                ('decrement_36_34V', models.FloatField()),
                ('max_voltage_discharge', models.FloatField()),
                ('min_voltage_charge', models.FloatField()),
                ('time_at_415V', models.FloatField()),
                ('time_constant_current', models.FloatField()),
                ('charging_time', models.FloatField()),
                ('rul', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
