# Generated by Django 5.1.6 on 2025-05-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batterydata',
            name='charging_time',
        ),
        migrations.RemoveField(
            model_name='batterydata',
            name='cycle_index',
        ),
        migrations.RemoveField(
            model_name='batterydata',
            name='decrement_36_34V',
        ),
        migrations.RemoveField(
            model_name='batterydata',
            name='discharge_time',
        ),
        migrations.RemoveField(
            model_name='batterydata',
            name='time_at_415V',
        ),
        migrations.RemoveField(
            model_name='batterydata',
            name='time_constant_current',
        ),
    ]
